nelmio_cors:
    defaults:
        origin_regex: true
        forced_allow_origin_value: '*'
        allow_origin: ['^http:\/\/localhost:[0-9]+', 'https://fustel.rookie.red']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/*': ~
