security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory: { memory: ~ }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        account_create:
            pattern: ^/account/signup
            anonymous: true
            stateless: true

        signin:
            pattern:  ^/account/signin
            stateless: true
            anonymous: true
            form_login:
                check_path:               /account/signin
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        main:
            anonymous: true
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/account/signin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account/signup, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY  }
